from snakemake.utils import min_version

min_version("6.10.0")


configfile: "config/config.yaml"


# declare https://github.com/b-brankovics/bwa-gatk-fasttree-smkwf as a module
module bwa_gatk_fasttree_smkwf:
    snakefile:
        github(
            "b-brankovics/bwa-gatk-fasttree-smkwf",
            path="workflow/Snakefile",
            branch="main",
        )
    config:
        config


include: "rules/common.smk"


# use all rules from https://github.com/b-brankovics/bwa-gatk-fasttree-smkwf
use rule * from bwa_gatk_fasttree_smkwf exclude all


rule all:
    default_target: True
    input:
        "results/snpeff/all.snvs.selected.vcf",
        "results/snpeff/mutation_table_snvs_wide.tsv",
        "results/snpeff/gene_mutations_all.tsv",


rule get_gbk:
    """
    Download data from NCBI and place it to correct location
    """
    output:
        gbk="resources/snpeff/{accession}/genes.gbk",
        snpeff_config="resources/snpeff/{accession}/snpeff.config",
        zip=temp("resources/datasets/{accession}.zip"),
        dir=temp(directory("resources/datasets/{accession}")),
    log:
        "logs/datasets/{accession}.log",
    # wildcard_constraints:
    #     sample=ACCESSION_SAMPLES
    conda:
        "envs/ncbi-datasets.yaml"
    params:
        accession=ref_id,
    shell:
        """
        datasets download genome accession {wildcards.accession} --include gbff --filename {output.zip} 2>{log}
        unzip {output.dir}.zip -d {output.dir} 2>>{log}
        mv {output.dir}/ncbi_dataset/data/{wildcards.accession}/genomic.gbff {output.gbk} 2>>{log}
        echo "{wildcards.accession}.genome: {wildcards.accession}" >{output.snpeff_config} 2>>{log}
        """


# Rule to create a SnpEff database for each gene
rule build_snpeff_db:
    input:
        gbk="resources/snpeff/{accession}/genes.gbk",
        snpeff_config="resources/snpeff/{accession}/snpeff.config",
    output:
        db="resources/snpeff/{accession}/snpEffectPredictor.bin",
    log:
        "logs/snpeff_build_db/{accession}.log",
    conda:
        "envs/snpeff.yaml"
    params:
        snpeff_dir=lambda w, output: os.path.dirname(os.path.dirname(output.db)),
    shell:
        """
        snpEff build -c {input.snpeff_config} -dataDir $PWD/{params.snpeff_dir} -genbank -v {wildcards.accession} >>{log} 2>&1
        """


# Annotate the filtered VCF file using SnpEff for each gene
rule snpeff_annotate_genes:
    input:
        vcf="results/filtered/all.{vartype}.selected.vcf.gz",
        snpeff_config=f"resources/snpeff/{ref_id}/snpeff.config",
        db=f"resources/snpeff/{ref_id}/snpEffectPredictor.bin",
    output:
        vcf="results/snpeff/all.{vartype}.selected.vcf",
        html="results/snpeff/all.{vartype}.selected_summary.html",
        csv="results/snpeff/all.{vartype}.selected_summary.csv",
    log:
        "logs/snpeff/{vartype}.log",
    conda:
        "envs/snpeff.yaml"
    params:
        snpeff_dir=lambda w, input: os.path.dirname(os.path.dirname(input.db)),
        ref_id=ref_id,
    shell:
        """
        snpEff -c {input.snpeff_config} -dataDir $PWD/{params.snpeff_dir} {params.ref_id} \
            -v {input.vcf} \
            -stats {output.html} \
            -csvStats {output.csv} \
            >{output.vcf} 2>{log}
        """


# Annotation file to SNP .tsv table
rule snp2tsv_table:
    input:
        vcf="results/snpeff/all.{vartype}.selected.vcf",
    output:
        batches=temp(directory("results/snps_snpeff_batches_{vartype}")),
    log:
        "logs/parse_snpeff/vcf2table/{vartype}.log",
    conda:
        "envs/bcftools.yaml"
    script:
        "scripts/vcf2table.sh"


# From table to neat table with Rscript, per gene
rule table2results:
    input:
        unpack(table2results_inputs),
    output:
        long="results/snpeff/mutation_table_{vartype}_long.tsv",
        wide="results/snpeff/mutation_table_{vartype}_wide.tsv",
    log:
        "logs/parse_snpeff/table2results/{vartype}.log",
    conda:
        "envs/R.yaml"
    script:
        "scripts/summarize_mutations.R"


rule snpeff_annotate_genes_all:
    input:
        vcf="results/genotyped/all.vcf.gz",
        snpeff_config=f"resources/snpeff/{ref_id}/snpeff.config",
        db=f"resources/snpeff/{ref_id}/snpEffectPredictor.bin",
    output:
        vcf="results/snpeff/all.selected.vcf",
        html="results/snpeff/all.selected_summary.html",
        csv="results/snpeff/all.selected_summary.csv",
    log:
        "logs/snpeff/all.log",
    conda:
        "envs/snpeff.yaml"
    params:
        snpeff_dir=lambda w, input: os.path.dirname(os.path.dirname(input.db)),
        ref_id=ref_id,
    shell:
        """
        snpEff -c {input.snpeff_config} -dataDir $PWD/{params.snpeff_dir} {params.ref_id} \
            -v {input.vcf} \
            -stats {output.html} \
            -csvStats {output.csv} \
            >{output.vcf} 2>{log}
        """


rule snp2tsv_table_all:
    input:
        vcf="results/snpeff/all.selected.vcf",
    output:
        tsv="results/snpeff/all.selected.tsv",
    log:
        "logs/parse_snpeff/vcf2table_old/all.log",
    conda:
        "envs/bcftools.yaml"
    script:
        "scripts/vcf2table_old.sh"


rule table2results_all:
    input:
        snpeff="results/snpeff/all.selected.tsv",
        genes="config/genes.tsv",
    output:
        wide="results/snpeff/gene_mutations_all.tsv",
    log:
        "logs/parse_snpeff/table2results_old/all.log",
    conda:
        "envs/R2.yaml"
    script:
        "scripts/mutation_correlation.R"
